name: Check for PopMart Draw

on:
  schedule:
    - cron: "*/5 * * * *" # Toutes les 5 minutes
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Run draw check
        id: draw
        run: |
          result=$(bash ./check_draw.sh)
          echo "result=$result" >> "$GITHUB_OUTPUT"

      - name: Send Discord notification if draw found
        if: steps.draw.outputs.result == 'true'
        run: |
          curl -X POST "$DISCORD_WEBHOOK" \
            -H "Content-Type: application/json" \
            -d "{\"content\": \"🧸 **Nouveau tirage détecté sur PopMart !** https://popmart.runfair.com/fr-FR/fr\"}"
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
